server.port=8081
spring.application.name=pharmacy-service

# Import centralized configuration from Spring Cloud Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Actuator Endpoints Configuration
management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.health.show-details=always
