server.port=8888
spring.application.name=config-server

# Remote GitHub repository configuration
spring.cloud.config.server.git.uri=https://github.com/anvvhe190784/MD04_SS09_Bai2.git
spring.cloud.config.server.git.search-paths=config-repo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
